FROM hypertools_4_2:latest

RUN cd / &&\
    git clone https://github.com/cubert-hyperspectral/cuvis.sdk.git &&\
    cd cuvis.sdk &&\
    git submodule update --init --recursive

RUN wget https://cloud.cubert-gmbh.de/index.php/s/m1WfR66TjcGl96z/download && \
    unzip download && \
	cd latest_release && \
    cd Ubuntu\ 20.04/  && \
	apt install ./cuviscommon_3.2.1-1.deb -y && \
	dpkg -i --force-overwrite ./libcuvis_3.2.1-1.deb

RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update

RUN apt install -y \
	doxygen \
	graphviz \
	swig 
	
RUN apt update -y

RUN apt upgrade -y

RUN cd /cuvis.sdk &&\
	git clone https://github.com/cubert-hyperspectral/cuvis.pyil.git &&\
    cd cuvis.pyil &&\
    git submodule update --init --recursive &&\
    python3.9 -m pip install . &&\
    mkdir build &&\
    cd build &&\
    cmake  -DCMAKE_BUILD_TYPE=Release -DDOXYGEN_BUILD_DOCUMENTATION=OFF -DPython_ROOT_DIR=/usr/bin/python3.9  .. &&\
    cmake --build . --target cuvis_pyil --config Release &&\
	cp ./_cuvis_pyil.so ../cuvis_il && \
	cp ./cuvis_il.py ../cuvis_il && \
    cd .. &&\
    python3.9 -m pip install . 

# below is a temp fix for the cuvis.python repo
RUN cd /cuvis.sdk/cuvis.python &&\
    git checkout main &&\
    python3.9 -m pip install  .

# this is how to pip install for python3.9 instead of the standard python environment
RUN python3.9 -m pip install matplotlib

# below is a temp fix until the cuvis.cpp repo is updated
RUN cd /cuvis.sdk/ &&\
    rm -r cuvis.cpp &&\
    git clone https://github.com/antmedellin/cuvis.cpp.git &&\
    cd cuvis.cpp &&\
    git fetch &&\
    git checkout patch-1
    
RUN echo 'alias python="/usr/bin/python3.9"' >> ~/.bashrc 
RUN echo 'alias python3="/usr/bin/python3.9"' >> ~/.bashrc 
RUN echo 'export CUVIS="/lib/cuvis"' >> ~/.bashrc 
RUN echo 'export CUVIS_DATA="/opt/cuvis"' >> ~/.bashrc 

WORKDIR /home

RUN cd /home &&\
    bash
