FROM hypertools_onnx:latest

RUN cd / &&\
    mkdir torch &&\
    cd torch/ &&\ 
    wget https://download.pytorch.org/libtorch/nightly/cpu/libtorch-shared-with-deps-latest.zip &&\
    unzip libtorch-shared-with-deps-2.2.1+cu121.zip 



WORKDIR /home

RUN cd /home &&\
    bash
