FROM nvidia/cuda:12.3.1-devel-ubuntu20.04


ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y \ 
    cmake \
    build-essential   \
    g++  \
    wget \
    unzip \
    libgtk2.0-dev \
    pkg-config  \
    libjsoncpp-dev \
    libcanberra-gtk-module \
    libgtk-3-dev \
    libboost-all-dev \
    glade  \
    git  


RUN mkdir -p opencv_build &&\
    cd opencv_build && \
    wget -O opencv.zip https://github.com/opencv/opencv/archive/4.2.0.zip && \
    wget -O opencv_contrib.zip https://github.com/opencv/opencv_contrib/archive/4.2.0.zip && \
    unzip opencv.zip &&\
    rm opencv.zip && \
    unzip opencv_contrib.zip &&\
    rm opencv_contrib.zip && \
    mkdir -p build && \ 
    cd build &&\
    cmake \
    -DOPENCV_ENABLE_NONFREE:BOOL=ON  \
    -DOPENCV_EXTRA_MODULES_PATH=../opencv_contrib-4.2.0/modules  ../opencv-4.2.0/     \
    -D OPENCV_GENERATE_PKGCONFIG=ON &&\
    make -j$(nproc) &&\
    make install && \
    ldconfig
 
RUN apt-get install -y \
    language-pack-en-base \
    libgdal-dev \
    python3-pip \
    python3-tk \
    libhdf5-dev \
    libtool \
    m4 \
    automake

RUN pip3 install \
    matplotlib 

RUN cd / &&\
    git clone git://git.code.sf.net/p/matio/matio &&\
    cd matio &&\
    mkdir build &&\
    cd build &&\
    cmake .. &&\
    cmake --build . &&\
    cmake --install .

RUN apt remove --purge --auto-remove cmake -y && \
    apt update && \
    apt install -y software-properties-common lsb-release && \
    apt clean all 

    
RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - |  tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null  && \
    apt-add-repository "deb https://apt.kitware.com/ubuntu/ $(lsb_release -cs) main"  && \
    apt update && \
    apt install kitware-archive-keyring -y && \
    rm /etc/apt/trusted.gpg.d/kitware.gpg && \
    apt-get update && \
    apt-get install -y \
    cmake \
    build-essential 

WORKDIR /home

